# Generated by Django 3.2.12 on 2023-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('reg_status', models.CharField(choices=[('OP', 'Открыта'), ('CL', 'Закрыта')], default='OP', max_length=2)),
                ('data', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Мероприятие',
            },
        ),
    ]
