# Generated by Django 3.2.12 on 2023-12-13 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0003_event_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORG', 'Организатор'), ('VOL', 'Волонтер'), ('PTC', 'Участник')], default='PTC', max_length=3)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
