# Generated by Django 3.2.12 on 2023-12-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_userevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
