# Generated by Django 4.2.7 on 2023-11-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(null=True)),
                ('email', models.EmailField(db_index=True, max_length=1000, unique=True)),
                ('user_registration_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
            },
        ),
    ]
