# Generated by Django 3.2.12 on 2023-12-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
