# Generated by Django 3.2.12 on 2023-12-13 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0006_userevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
